version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
  commands:
   - pip install --upgrade pip
   # Install dependencies needed for running the static analysis
   - pip install -r requirements.txt pylint
 pre_build:
  commands:
   - python --version
   - cd furniture
   - pylint *.py
   - cd ..
   - cd OnlineFurnitureShop
   - pylint *.py
artifacts:
 files:
  - '**/*'